### ISSUE TITLE
Bomb site blocker

### ISSUE THREAD

**Issue by brutalcinikola** [Quake1011/CS2-plugins-lua#8]
this is my config

		"available_plant"			"A"				// A - only A plant available | B - only B plant available | RANDOM - random plant will blocked 
		"ct_need_to_unlock"			"5"				// CTs need for plant will unlocked
		"t_need_to_unlock"			"2"				// Ts need for plant will unlocked
		
		But site A gets blocked, it looks like its random. I just want to block bomsite B

**Comment by rcon420** [comment]
i just wanted to open same issue. radom selection works anyway when A is selected only.

**Comment by Quake1011** [comment]
> i just wanted to open same issue. radom selection works anyway when A is selected only.

Are you using the advertisement?

**Comment by rcon420** [comment]
> > i just wanted to open same issue. radom selection works anyway when A is selected only.
> 
> Are you using the advertisement?

yes I do.

**Comment by Quake1011** [comment]
I fixed this in last version. Can check on yours?

**Comment by rcon420** [comment]
> I fixed this in last version. Can check on yours?

checked didnt fix the problem u can add me on dc: @oligarhs420

**Comment by Quake1011** [comment]
Fixed
